// Generated by scripts/build-catalog.py; edit vesper/catalog.json.
export const CARTRIDGES = [
  {
    "id": "orbit",
    "name": "ORBIT LOCK",
    "subtitle": "Catch a wandering satellite.",
    "description": "Acquire the amber gate as your satellite crosses it. Each lock tightens the window, and later sectors reverse the orbit and set the gate drifting. Three missed alignments end the expedition.",
    "controls": "PRESS AT THE GATE",
    "category": "PLAY / PRECISION",
    "glyph": 0,
    "factory": "OrbitLock",
    "voice": [
      "orbit"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "runner",
    "name": "MOONRUNNER",
    "subtitle": "Leave footprints in the dark.",
    "description": "Cross a crystal desert with a stubborn little survey robot. Tap to hop; hold for height, because tall walls and long mesas need a held jump. Two shields forgive early mistakes. The lamps fill as the next obstacle closes. Your best distance is saved.",
    "controls": "TAP TO JUMP · HOLD FOR HEIGHT",
    "category": "PLAY / RUNNER",
    "glyph": 1,
    "factory": "Moonrunner",
    "voice": [
      "runner"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "drift",
    "name": "UNDERTOW",
    "subtitle": "Follow the silent current.",
    "description": "Pilot a small craft through an impossible ocean. Hold to rise, release to sink, and thread the openings between ancient columns. The hull survives a bump or two. The lamps show your depth and where the next opening is.",
    "controls": "HOLD TO RISE · RELEASE TO SINK",
    "category": "PLAY / FLIGHT",
    "glyph": 2,
    "factory": "Undertow",
    "voice": [
      "drift"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "echo",
    "name": "ECHO VAULT",
    "subtitle": "Learn Morse by keying words.",
    "description": "Transmissions approach the vault: key each word in Morse before its timer runs out (tap a dot, hold a dash). It starts with four letters and opens one more whenever the ones you have are holding up; a letter’s code shows at once while it is new and later as it grows stronger. Echo transmissions are heard, not shown: key back what you heard, or hold for a second to hear it again. Letters learned in Signal School are open here too. Thirty transmissions open the vault; hold on the title for the code card.",
    "controls": "TAP A DOT · HOLD A DASH",
    "category": "PLAY / LEARNING",
    "glyph": 3,
    "factory": "EchoVault",
    "voice": [
      "echo"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "record": {
      "words": "Words",
      "letters": "Letters",
      "accuracy": "Clean %",
      "cpm": "Letters a minute",
      "score": "Score"
    }
  },
  {
    "id": "reaction",
    "name": "LIGHT TRIAL",
    "subtitle": "Measure the space before action.",
    "description": "Press to arm a trial. Wait for the middle physical light to turn green. ESP32 button trials use the node clock; keyboard trials use approximate screen timing.",
    "controls": "WAIT FOR LIGHT II · THEN PRESS",
    "category": "PLAY / REACTION",
    "glyph": 4,
    "factory": "LightTrial",
    "voice": [
      "lights"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "glyphs",
    "name": "GLYPH ARCHIVE",
    "subtitle": "Learn real symbols, card by card.",
    "description": "Four wings: Braille letters, the Greek alphabet, chemical element symbols and the radio alphabet. Each card shows a symbol and a meaning: tap if they match, hold if they do not, before the card runs out. New entries are shown first, a few at a time, and come back on a spaced schedule until they are mastered; wrong pairs are chosen to be easy to confuse. Hold on the title to change wing.",
    "controls": "TAP: MATCH · HOLD: NO MATCH",
    "category": "PLAY / LEARNING",
    "glyph": 5,
    "factory": "GlyphVault",
    "voice": [
      "glyphs"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "record": {
      "wing": "Wing",
      "cards": "Cards",
      "correct": "Right",
      "accuracy": "Accuracy %",
      "score": "Score"
    }
  },
  {
    "id": "pulsar",
    "name": "PULSAR",
    "subtitle": "Keep time with a dying star.",
    "description": "Beats fall down three lanes toward the strike line. Tap on the beat; hold through the long signals. The song lasts about two minutes, if you keep the signal stable.",
    "controls": "TAP ON THE BEAT · HOLD LONG SIGNALS · LAMPS SWELL FIRST",
    "category": "PLAY / RHYTHM",
    "glyph": 3,
    "factory": "Pulsar",
    "voice": [
      "rhythm"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "icon": "<path d=\"M4 24h9l4-12 6 24 5-18 3 6h13\"/><circle cx=\"24\" cy=\"24\" r=\"21\" stroke-dasharray=\"2 5\"/><circle cx=\"43\" cy=\"24\" r=\"2\" fill=\"currentColor\"/>",
    "record": {
      "score": "Score",
      "combo": "Best combo",
      "accuracy": "Accuracy %",
      "phrases": "Phrases reached"
    }
  },
  {
    "id": "perihelion",
    "name": "PERIHELION",
    "subtitle": "Swing between small suns.",
    "description": "Hold to tether to the nearest anchor and swing. Release to fly on. Cross six regions to the perihelion, find relics, earn feats. Hold on the title for the hangar.",
    "controls": "HOLD TO TETHER · RELEASE TO FLY · HOLD ON TITLE: HANGAR",
    "category": "PLAY / MOMENTUM",
    "glyph": 0,
    "factory": "Perihelion",
    "voice": [
      "swing"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "icon": "<circle cx=\"30\" cy=\"12\" r=\"5\"/><circle cx=\"30\" cy=\"12\" r=\"1.5\" fill=\"currentColor\"/><path d=\"M30 17L10 34\"/><path d=\"M10 34Q24 46 40 38\" stroke-dasharray=\"3 3\"/><path d=\"M40 38l-6-1M40 38l-3 5\"/><circle cx=\"10\" cy=\"34\" r=\"3\" fill=\"currentColor\"/>",
    "record": {
      "mkm": "Distance / Mkm",
      "chain": "Best chain",
      "catches": "Anchors caught",
      "relics": "Relics",
      "region": "Furthest this run"
    }
  },
  {
    "id": "descent",
    "name": "DESCENT",
    "subtitle": "Set down gently, or not at all.",
    "description": "Hold to burn against gravity and settle on the pad before the fuel runs out. The lamps are your descent-rate indicator.",
    "controls": "HOLD TO BURN · RELEASE TO FALL",
    "category": "PLAY / LANDER",
    "glyph": 1,
    "factory": "Descent",
    "icon": "<path d=\"M17 22l2-9h10l2 9zM17 22l-5 8M31 22l5 8M10 30h6M32 30h6M20 22h8\"/><path d=\"M24 26l-3 6h6z\"/><path d=\"M4 42h40M14 42v-2M34 42v-2\"/><circle cx=\"38\" cy=\"9\" r=\"2\" fill=\"currentColor\"/>",
    "record": {
      "score": "Score",
      "sites": "Sites cleared",
      "fuel": "Best fuel left %"
    },
    "voice": [
      "lander"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "ricochet",
    "name": "RICOCHET",
    "subtitle": "Break the lattice.",
    "description": "The paddle never stops. Tap to reverse it and keep the signal bouncing through the lattice. The first chamber is practice.",
    "controls": "TAP TO REVERSE THE PADDLE",
    "category": "PLAY / BREAKOUT",
    "glyph": 5,
    "factory": "Ricochet",
    "voice": [
      "breakout"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "icon": "<path d=\"M5 6h10v6H5zM19 6h10v6H19zM33 6h10v6H33zM12 15h10v6H12zM26 15h10v6H26z\"/><path d=\"M31 42l-6-11\" stroke-dasharray=\"2 3\"/><path d=\"M13 44h19\"/><circle cx=\"24\" cy=\"29\" r=\"2.5\" fill=\"currentColor\"/>",
    "record": {
      "score": "Score",
      "chamber": "Chamber reached",
      "cells": "Cells broken",
      "chain": "Best chain (x)"
    }
  },
  {
    "id": "helix",
    "name": "HELIX",
    "subtitle": "Grow without crossing yourself.",
    "description": "A signal thread that only turns one way. Tap to turn, gather fragments, and do not touch your own trail. The walls are soft for the first twenty seconds.",
    "controls": "TAP TO TURN",
    "category": "PLAY / TRAIL",
    "glyph": 2,
    "factory": "Helix",
    "voice": [
      "snake"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "icon": "<path d=\"M6 40V8h30v26H16V18h12v6\"/><circle cx=\"22\" cy=\"24\" r=\"2\" fill=\"currentColor\"/><path d=\"M40 40l3-3M40 37l3 3\"/>",
    "record": {
      "score": "Score",
      "fragments": "Fragments",
      "longest": "Longest thread",
      "milestone": "Milestone"
    }
  },
  {
    "id": "ballista",
    "name": "BALLISTA",
    "subtitle": "Launch probes through the wind.",
    "description": "The aim sweeps by itself. Hold to charge, release to launch, and allow for the wind.",
    "controls": "HOLD TO CHARGE · RELEASE TO LAUNCH",
    "category": "PLAY / ARTILLERY",
    "glyph": 4,
    "factory": "Ballista",
    "icon": "<path d=\"M5 38h38M8 38l4-6h8l4 6\"/><path d=\"M16 31l8-8\" stroke-width=\"4\"/><path d=\"M22 20C27 8 36 8 40 25\" stroke-dasharray=\"3 4\"/><circle cx=\"40\" cy=\"31\" r=\"6\"/><circle cx=\"40\" cy=\"31\" r=\"2\" fill=\"currentColor\"/>",
    "record": {
      "score": "Score",
      "stations": "Stations cleared",
      "shots": "Probes launched",
      "accuracy": "Accuracy %"
    },
    "voice": [
      "launcher"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "tideline",
    "name": "TIDELINE",
    "subtitle": "Something is on the line.",
    "description": "Charge a cast, wait for the bite, then hold and release to keep the catch zone on the fish. Alien waters, thirty species, a field log and better gear. Playable by the lamps alone.",
    "controls": "HOLD TO CAST AND LIFT THE ZONE · TAP FOR GEAR AND LOG",
    "category": "PLAY / ANGLING",
    "glyph": 2,
    "factory": "Tideline",
    "voice": [
      "fishing"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "icon": "<path d=\"M6 40L30 8\"/><path d=\"M30 8Q40 12 38 28\"/><path d=\"M38 28v4a3 3 0 1 1-3-3\"/><path d=\"M6 44Q14 41 22 44T38 44T46 43\" stroke-dasharray=\"3 3\"/><circle cx=\"28\" cy=\"36\" r=\"1.5\" fill=\"currentColor\"/>",
    "record": {
      "recorded": "Species recorded",
      "score": "Catalogue score",
      "landed": "Fish landed",
      "tides": "Tides completed"
    }
  },
  {
    "id": "outpost",
    "name": "OUTPOST",
    "subtitle": "Build something that runs without you.",
    "description": "Tap to gather signal, and every tap plays the next note of a melody: a songbook of old tunes and endless composed ones, played at your own tempo. Hold to open the build ring: buy machines, check statistics and goals, run research, choose the tune. Relocations and expeditions deepen the station, and it keeps working while you are away (up to eight hours, more with upgrades).",
    "controls": "TAP TO GATHER AND PLAY · HOLD FOR THE RING",
    "category": "PLAY / INCREMENTAL",
    "glyph": 5,
    "icon": "<path d=\"M4 40h40\"/><path d=\"M12 40V28l5-9 5 9v12\"/><path d=\"M30 40V24M26 24h8M30 24l-3-8M30 24l3-8\"/><circle cx=\"30\" cy=\"10\" r=\"2\" fill=\"currentColor\"/><path d=\"M36 6a8 8 0 0 1 0 8M39 3a12 12 0 0 1 0 14\" stroke-dasharray=\"2 3\"/>",
    "record": {
      "signal": "Lifetime signal",
      "bearings": "Bearings earned",
      "relocations": "Relocations"
    },
    "factory": "Outpost",
    "voice": [
      "station"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "morse",
    "name": "SIGNAL SCHOOL",
    "subtitle": "Speak in dots and dashes.",
    "description": "Learn the alphabet through a progressive Morse lesson. A letter moves on after two correct answers in a row. The lights and optional sidetone follow your key, and replay the right signal after a mistake. Beginner letter gaps are deliberately forgiving.",
    "controls": "TAP A DOT · HOLD A DASH",
    "category": "INSTRUMENT / TELEGRAPHY",
    "glyph": 3,
    "factory": "MorseSchool",
    "voice": [
      "morse"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "timers",
    "name": "CHRONOMETER",
    "subtitle": "Keep time beyond this screen.",
    "description": "Create up to eight persistent background timers. The nearest one is shown large and drains across the three lamps while this screen is open. A completed timer announces itself without interrupting a game’s physical lights.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "INSTRUMENT / TIME",
    "glyph": 0,
    "factory": "Timers",
    "voice": [],
    "capabilities": [
      "timers",
      "progress"
    ]
  },
  {
    "id": "transcribe",
    "name": "FIELD NOTES",
    "subtitle": "Let the room tell its story.",
    "description": "Local speech-to-text with visible microphone status, saved sessions, and text export. Recording continues when you leave this screen; mute is always in the system menu.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "INSTRUMENT / TRANSCRIPTION",
    "glyph": 2,
    "factory": "Transcription",
    "voice": [
      "notes"
    ],
    "capabilities": [
      "microphone",
      "notes"
    ]
  },
  {
    "id": "environment",
    "name": "ATMOSPHERE",
    "subtitle": "Observe the world around you.",
    "description": "Temperature and humidity from your SHT3x with dew point, feels-like, absolute humidity, today’s extremes, the hourly trend and a comfort verdict shown on the lamps. History charts for 24 hours, 7 days and 30 days. Simulator readings are explicitly marked and stored separately.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "INSTRUMENT / ENVIRONMENT",
    "glyph": 4,
    "factory": "Environment",
    "voice": [
      "environment"
    ],
    "capabilities": [
      "sensor"
    ]
  },
  {
    "id": "diagnostics",
    "name": "NODE SCOPE",
    "subtitle": "Look inside the instrument.",
    "description": "Live button state, node link and firmware, sensor bus diagnostics, light-channel checks with the lamp level, microphone level, sensor readings, and communication counters.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "SYSTEM / DIAGNOSTICS",
    "glyph": 1,
    "factory": "Diagnostics",
    "voice": [
      "diagnostics"
    ],
    "capabilities": [
      "button",
      "lights",
      "microphone",
      "sensor"
    ]
  },
  {
    "id": "settings",
    "name": "CALIBRATION",
    "subtitle": "Make the console your own.",
    "description": "Sound, volume, phosphor texture, reduced motion, Morse speed, and button hold duration. All controls work with one button.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "SYSTEM / SETTINGS",
    "glyph": 5,
    "factory": "Settings",
    "voice": [
      "settings"
    ],
    "capabilities": [
      "settings"
    ]
  },
  {
    "id": "lantern",
    "name": "LANTERN",
    "subtitle": "Carry a little light.",
    "description": "The three lamps as a lamp: colours, brightness and slow scenes, with a night-light that switches itself off.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "INSTRUMENT / LIGHT",
    "glyph": 4,
    "icon": "<path d=\"M19 11q5-8 10 0\"/><path d=\"M17 12h14l4 7v15l-4 6H17l-4-6V19z\"/><path d=\"M13 19h22M13 34h22M15 43h18\"/><circle cx=\"18\" cy=\"27\" r=\"1.6\" fill=\"currentColor\"/><circle cx=\"24\" cy=\"27\" r=\"1.6\" fill=\"currentColor\"/><circle cx=\"30\" cy=\"27\" r=\"1.6\" fill=\"currentColor\"/>",
    "factory": "Lantern",
    "voice": [
      "lamp"
    ],
    "capabilities": [
      "lights",
      "progress"
    ]
  },
  {
    "id": "cadence",
    "name": "CADENCE",
    "subtitle": "Count the beat and the laps.",
    "description": "A metronome with tap tempo, a stopwatch with laps, and work/rest intervals shown on the lamps.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "INSTRUMENT / TEMPO",
    "glyph": 3,
    "factory": "Cadence",
    "voice": [
      "metronome",
      "timer"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "icon": "<path d=\"M16 42h16l5-30H11z\"/><path d=\"M24 36L33 8\"/><circle cx=\"30\" cy=\"19\" r=\"2.5\" fill=\"currentColor\"/><path d=\"M19 42v-5M29 42v-5\"/><path d=\"M40 20q4 4 0 8M43 17q7 7 0 14\"/>"
  },
  {
    "id": "ephemeris",
    "name": "EPHEMERIS",
    "subtitle": "Know where the sky is.",
    "description": "The time, the Moon's phase, sunrise and sunset for your location, and a small orrery. All computed locally.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "INSTRUMENT / SKY",
    "glyph": 0,
    "factory": "Ephemeris",
    "icon": "<path d=\"M4 34h40\"/><path d=\"M12 34a12 12 0 0 1 24 0\"/><path d=\"M24 16v-5M10 22l-3-3M38 22l3-3\"/><path d=\"M38 5a6 6 0 1 0 5 9 5 5 0 0 1-5-9z\"/><circle cx=\"8\" cy=\"42\" r=\"1.5\" fill=\"currentColor\"/><circle cx=\"24\" cy=\"42\" r=\"1.5\" fill=\"currentColor\"/><circle cx=\"40\" cy=\"42\" r=\"1.5\" fill=\"currentColor\"/>",
    "voice": [],
    "capabilities": [
      "progress"
    ]
  },
  {
    "id": "resonance",
    "name": "RESONANCE",
    "subtitle": "See what the room sounds like.",
    "description": "Sound level, spectrum and pitch from the microphone. Nothing is recognised or stored.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "INSTRUMENT / SOUND",
    "glyph": 2,
    "factory": "Resonance",
    "icon": "<rect x=\"5\" y=\"9\" width=\"38\" height=\"30\" rx=\"5\"/><path d=\"M9 24h5l3-9 4 18 4-22 4 20 3-11 2 4h6\"/><path d=\"M9 34h30\" stroke-dasharray=\"1 4\"/><circle cx=\"39\" cy=\"14\" r=\"1.6\" fill=\"currentColor\"/>",
    "voice": [
      "sound"
    ],
    "capabilities": [
      "microphone",
      "lights"
    ]
  },
  {
    "id": "oracle",
    "name": "ORACLE",
    "subtitle": "Ask the dark for a number.",
    "description": "Dice, coins, random picks and yes-or-no answers, rolled across the lamps.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "INSTRUMENT / CHANCE",
    "glyph": 5,
    "factory": "Oracle",
    "icon": "<rect x=\"7\" y=\"7\" width=\"34\" height=\"34\" rx=\"7\"/><circle cx=\"17\" cy=\"17\" r=\"2.4\" fill=\"currentColor\"/><circle cx=\"31\" cy=\"17\" r=\"2.4\" fill=\"currentColor\"/><circle cx=\"24\" cy=\"24\" r=\"2.4\" fill=\"currentColor\"/><circle cx=\"17\" cy=\"31\" r=\"2.4\" fill=\"currentColor\"/><circle cx=\"31\" cy=\"31\" r=\"2.4\" fill=\"currentColor\"/><path d=\"M2 24h2M44 24h2M24 2v2M24 44v2\"/>",
    "voice": [
      "dice"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "telemetry",
    "name": "TELEMETRY",
    "subtitle": "Listen to the machine itself.",
    "description": "Health of the Pi and the node: temperature, load, memory, storage, link and firmware.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "SYSTEM / HEALTH",
    "glyph": 1,
    "factory": "Telemetry",
    "icon": "<path d=\"M6 38a18 18 0 1 1 36 0\"/><path d=\"M24 38l8-14\"/><path d=\"M10 38h4M34 38h4M24 20v4M12 26l3 2M36 26l-3 2\"/><circle cx=\"24\" cy=\"38\" r=\"2\" fill=\"currentColor\"/><path d=\"M8 44h32\" stroke-dasharray=\"3 3\"/>",
    "voice": [
      "system"
    ],
    "capabilities": [
      "sensor"
    ]
  }
];
export const SECTORS = [{"name": "PLAY", "apps": ["perihelion", "orbit", "runner", "pulsar", "tideline"]}, {"name": "PLAY II", "apps": ["drift", "descent", "ballista", "ricochet", "helix"]}, {"name": "PLAY III", "apps": ["outpost", "reaction", "echo", "glyphs"]}, {"name": "INSTRUMENTS", "apps": ["morse", "cadence", "transcribe", "environment"]}, {"name": "INSTRUMENTS II", "apps": ["lantern", "resonance", "oracle"]}];
export const SYSTEM_APPS = ["settings", "diagnostics", "telemetry"];
export const DEFAULT_SETTINGS = {
  "sound": true,
  "volume": 0.25,
  "crt": true,
  "reducedMotion": false,
  "morseWpm": 10,
  "holdMs": 650,
  "gesturePace": "standard",
  "scanMs": 850,
  "tempUnit": "F",
  "tempOffset": 0,
  "lampLevel": "medium",
  "lampAmbient": true
};
