// Generated by scripts/build-catalog.py; edit vesper/catalog.json.
export const CARTRIDGES = [
  {
    "id": "orbit",
    "name": "ORBIT LOCK",
    "subtitle": "Catch a wandering satellite.",
    "description": "Acquire the amber gate as your satellite crosses it. Each lock tightens the window, and later sectors reverse the orbit and set the gate drifting. Three missed alignments end the expedition.",
    "controls": "PRESS AT THE GATE",
    "category": "PLAY / PRECISION",
    "glyph": 0,
    "factory": "OrbitLock",
    "voice": [
      "orbit"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "runner",
    "name": "MOONRUNNER",
    "subtitle": "Leave footprints in the dark.",
    "description": "Cross a crystal desert with a stubborn little survey robot. Tap to hop; hold for height, because tall walls and long mesas need a held jump. Two shields forgive early mistakes. The lamps fill as the next obstacle closes. Your best distance is saved.",
    "controls": "TAP TO JUMP · HOLD FOR HEIGHT",
    "category": "PLAY / RUNNER",
    "glyph": 1,
    "factory": "Moonrunner",
    "voice": [
      "runner"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "drift",
    "name": "UNDERTOW",
    "subtitle": "Follow the silent current.",
    "description": "Pilot a small craft through an impossible ocean. Hold to rise, release to sink, and thread the openings between ancient columns. The hull survives a bump or two. The lamps show your depth and where the next opening is.",
    "controls": "HOLD TO RISE · RELEASE TO SINK",
    "category": "PLAY / FLIGHT",
    "glyph": 2,
    "factory": "Undertow",
    "voice": [
      "drift"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "echo",
    "name": "ECHO VAULT",
    "subtitle": "Return the signal you receive.",
    "description": "Watch and hear a growing pattern. Reproduce it with short taps and long holds; the lamps fill while you hold and turn cyan when the vault hears a long pulse. Each successful sequence opens another chamber.",
    "controls": "SHORT TAP / LONG HOLD",
    "category": "PLAY / MEMORY",
    "glyph": 3,
    "factory": "EchoVault",
    "voice": [
      "echo"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "reaction",
    "name": "LIGHT TRIAL",
    "subtitle": "Measure the space before action.",
    "description": "Press to arm a trial. Wait for the middle physical light to turn green. ESP32 button trials use the node clock; keyboard trials use approximate screen timing.",
    "controls": "WAIT FOR LIGHT II · THEN PRESS",
    "category": "PLAY / REACTION",
    "glyph": 4,
    "factory": "LightTrial",
    "voice": [
      "lights"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "glyphs",
    "name": "GLYPH ARCHIVE",
    "subtitle": "Remember a forgotten language.",
    "description": "Memorize the inscription before it disappears. The cursor cycles through six glyphs; press to rebuild the sequence. Three mistakes seal the archive.",
    "controls": "PRESS TO CHOOSE THE LIT GLYPH",
    "category": "PLAY / PUZZLE",
    "glyph": 5,
    "factory": "GlyphVault",
    "voice": [
      "glyphs"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "pulsar",
    "name": "PULSAR",
    "subtitle": "Keep time with a dying star.",
    "description": "Beats fall down three lanes toward the strike line. Tap on the beat; hold through the long signals. The song lasts about two minutes, if you keep the signal stable.",
    "controls": "TAP ON THE BEAT · HOLD LONG SIGNALS · LAMPS SWELL FIRST",
    "category": "PLAY / RHYTHM",
    "glyph": 3,
    "factory": "Pulsar",
    "voice": [
      "rhythm"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "icon": "<path d=\"M4 24h9l4-12 6 24 5-18 3 6h13\"/><circle cx=\"24\" cy=\"24\" r=\"21\" stroke-dasharray=\"2 5\"/><circle cx=\"43\" cy=\"24\" r=\"2\" fill=\"currentColor\"/>",
    "record": {
      "score": "Score",
      "combo": "Best combo",
      "accuracy": "Accuracy %",
      "phrases": "Phrases reached"
    }
  },
  {
    "id": "perihelion",
    "name": "PERIHELION",
    "subtitle": "Swing between small suns.",
    "description": "Hold to tether to the nearest anchor and swing. Release to fly on. Cross six regions to the perihelion, find relics, earn feats. Hold on the title for the hangar.",
    "controls": "HOLD TO TETHER · RELEASE TO FLY · HOLD ON TITLE: HANGAR",
    "category": "PLAY / MOMENTUM",
    "glyph": 0,
    "factory": "Perihelion",
    "voice": [
      "swing"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "icon": "<circle cx=\"30\" cy=\"12\" r=\"5\"/><circle cx=\"30\" cy=\"12\" r=\"1.5\" fill=\"currentColor\"/><path d=\"M30 17L10 34\"/><path d=\"M10 34Q24 46 40 38\" stroke-dasharray=\"3 3\"/><path d=\"M40 38l-6-1M40 38l-3 5\"/><circle cx=\"10\" cy=\"34\" r=\"3\" fill=\"currentColor\"/>",
    "record": {
      "mkm": "Distance / Mkm",
      "chain": "Best chain",
      "catches": "Anchors caught",
      "relics": "Relics",
      "region": "Furthest this run"
    }
  },
  {
    "id": "descent",
    "name": "DESCENT",
    "subtitle": "Set down gently, or not at all.",
    "description": "Hold to burn against gravity and settle on the pad before the fuel runs out. The lamps are your descent-rate indicator.",
    "controls": "HOLD TO BURN · RELEASE TO FALL",
    "category": "PLAY / LANDER",
    "glyph": 1,
    "factory": "Descent",
    "icon": "<path d=\"M17 22l2-9h10l2 9zM17 22l-5 8M31 22l5 8M10 30h6M32 30h6M20 22h8\"/><path d=\"M24 26l-3 6h6z\"/><path d=\"M4 42h40M14 42v-2M34 42v-2\"/><circle cx=\"38\" cy=\"9\" r=\"2\" fill=\"currentColor\"/>",
    "record": {
      "score": "Score",
      "sites": "Sites cleared",
      "fuel": "Best fuel left %"
    },
    "voice": [
      "lander"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "ricochet",
    "name": "RICOCHET",
    "subtitle": "Break the lattice.",
    "description": "The paddle never stops. Tap to reverse it and keep the signal bouncing through the lattice. The first chamber is practice.",
    "controls": "TAP TO REVERSE THE PADDLE",
    "category": "PLAY / BREAKOUT",
    "glyph": 5,
    "factory": "Ricochet",
    "voice": [
      "breakout"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "icon": "<path d=\"M5 6h10v6H5zM19 6h10v6H19zM33 6h10v6H33zM12 15h10v6H12zM26 15h10v6H26z\"/><path d=\"M31 42l-6-11\" stroke-dasharray=\"2 3\"/><path d=\"M13 44h19\"/><circle cx=\"24\" cy=\"29\" r=\"2.5\" fill=\"currentColor\"/>",
    "record": {
      "score": "Score",
      "chamber": "Chamber reached",
      "cells": "Cells broken",
      "chain": "Best chain (x)"
    }
  },
  {
    "id": "helix",
    "name": "HELIX",
    "subtitle": "Grow without crossing yourself.",
    "description": "A signal thread that only turns one way. Tap to turn, gather fragments, and do not touch your own trail. The walls are soft for the first twenty seconds.",
    "controls": "TAP TO TURN",
    "category": "PLAY / TRAIL",
    "glyph": 2,
    "factory": "Helix",
    "voice": [
      "snake"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "icon": "<path d=\"M6 40V8h30v26H16V18h12v6\"/><circle cx=\"22\" cy=\"24\" r=\"2\" fill=\"currentColor\"/><path d=\"M40 40l3-3M40 37l3 3\"/>",
    "record": {
      "score": "Score",
      "fragments": "Fragments",
      "longest": "Longest thread",
      "milestone": "Milestone"
    }
  },
  {
    "id": "ballista",
    "name": "BALLISTA",
    "subtitle": "Launch probes through the wind.",
    "description": "The aim sweeps by itself. Hold to charge, release to launch, and allow for the wind.",
    "controls": "HOLD TO CHARGE · RELEASE TO LAUNCH",
    "category": "PLAY / ARTILLERY",
    "glyph": 4,
    "factory": "Ballista",
    "icon": "<path d=\"M5 38h38M8 38l4-6h8l4 6\"/><path d=\"M16 31l8-8\" stroke-width=\"4\"/><path d=\"M22 20C27 8 36 8 40 25\" stroke-dasharray=\"3 4\"/><circle cx=\"40\" cy=\"31\" r=\"6\"/><circle cx=\"40\" cy=\"31\" r=\"2\" fill=\"currentColor\"/>",
    "record": {
      "score": "Score",
      "stations": "Stations cleared",
      "shots": "Probes launched",
      "accuracy": "Accuracy %"
    },
    "voice": [
      "launcher"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "tideline",
    "name": "TIDELINE",
    "subtitle": "Something is on the line.",
    "description": "Charge a cast, wait for the bite, then hold and release to keep the catch zone on the fish. Alien waters, thirty species, a field log and better gear. Playable by the lamps alone.",
    "controls": "HOLD TO CAST AND LIFT THE ZONE · TAP FOR GEAR AND LOG",
    "category": "PLAY / ANGLING",
    "glyph": 2,
    "factory": "Tideline",
    "voice": [
      "fishing"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "icon": "<path d=\"M6 40L30 8\"/><path d=\"M30 8Q40 12 38 28\"/><path d=\"M38 28v4a3 3 0 1 1-3-3\"/><path d=\"M6 44Q14 41 22 44T38 44T46 43\" stroke-dasharray=\"3 3\"/><circle cx=\"28\" cy=\"36\" r=\"1.5\" fill=\"currentColor\"/>",
    "record": {
      "recorded": "Species recorded",
      "score": "Catalogue score",
      "landed": "Fish landed",
      "tides": "Tides completed"
    }
  },
  {
    "id": "outpost",
    "name": "OUTPOST",
    "subtitle": "Build something that runs without you.",
    "description": "Tap to gather signal, and every tap plays the next note of a melody: a songbook of old tunes and endless composed ones, played at your own tempo. Hold to open the build ring: buy machines, check statistics and goals, run research, choose the tune. Relocations and expeditions deepen the station, and it keeps working while you are away (up to eight hours, more with upgrades).",
    "controls": "TAP TO GATHER AND PLAY · HOLD FOR THE RING",
    "category": "PLAY / INCREMENTAL",
    "glyph": 5,
    "icon": "<path d=\"M4 40h40\"/><path d=\"M12 40V28l5-9 5 9v12\"/><path d=\"M30 40V24M26 24h8M30 24l-3-8M30 24l3-8\"/><circle cx=\"30\" cy=\"10\" r=\"2\" fill=\"currentColor\"/><path d=\"M36 6a8 8 0 0 1 0 8M39 3a12 12 0 0 1 0 14\" stroke-dasharray=\"2 3\"/>",
    "record": {
      "signal": "Lifetime signal",
      "bearings": "Bearings earned",
      "relocations": "Relocations"
    },
    "factory": "Outpost",
    "voice": [
      "station"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "morse",
    "name": "SIGNAL SCHOOL",
    "subtitle": "Speak in dots and dashes.",
    "description": "Learn the alphabet through a progressive Morse lesson. A letter moves on after two correct answers in a row. The lights and optional sidetone follow your key, and replay the right signal after a mistake. Beginner letter gaps are deliberately forgiving.",
    "controls": "TAP A DOT · HOLD A DASH",
    "category": "INSTRUMENT / TELEGRAPHY",
    "glyph": 3,
    "factory": "MorseSchool",
    "voice": [
      "morse"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "timers",
    "name": "CHRONOMETER",
    "subtitle": "Keep time beyond this screen.",
    "description": "Create up to eight persistent background timers. The nearest one is shown large and drains across the three lamps while this screen is open. A completed timer announces itself without interrupting a game’s physical lights.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "INSTRUMENT / TIME",
    "glyph": 0,
    "factory": "Timers",
    "voice": [],
    "capabilities": [
      "timers",
      "progress"
    ]
  },
  {
    "id": "transcribe",
    "name": "FIELD NOTES",
    "subtitle": "Let the room tell its story.",
    "description": "Local speech-to-text with visible microphone status, saved sessions, and text export. Recording continues when you leave this screen; mute is always in the system menu.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "INSTRUMENT / TRANSCRIPTION",
    "glyph": 2,
    "factory": "Transcription",
    "voice": [
      "notes"
    ],
    "capabilities": [
      "microphone",
      "notes"
    ]
  },
  {
    "id": "environment",
    "name": "ATMOSPHERE",
    "subtitle": "Observe the world around you.",
    "description": "Temperature and humidity from your SHT3x with dew point, feels-like, absolute humidity, today’s extremes, the hourly trend and a comfort verdict shown on the lamps. History charts for 24 hours, 7 days and 30 days. Simulator readings are explicitly marked and stored separately.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "INSTRUMENT / ENVIRONMENT",
    "glyph": 4,
    "factory": "Environment",
    "voice": [
      "environment"
    ],
    "capabilities": [
      "sensor"
    ]
  },
  {
    "id": "diagnostics",
    "name": "NODE SCOPE",
    "subtitle": "Look inside the instrument.",
    "description": "Live button state, node link and firmware, sensor bus diagnostics, light-channel checks with the lamp level, microphone level, sensor readings, and communication counters.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "SYSTEM / DIAGNOSTICS",
    "glyph": 1,
    "factory": "Diagnostics",
    "voice": [
      "diagnostics"
    ],
    "capabilities": [
      "button",
      "lights",
      "microphone",
      "sensor"
    ]
  },
  {
    "id": "settings",
    "name": "CALIBRATION",
    "subtitle": "Make the console your own.",
    "description": "Sound, volume, phosphor texture, reduced motion, Morse speed, and button hold duration. All controls work with one button.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "SYSTEM / SETTINGS",
    "glyph": 5,
    "factory": "Settings",
    "voice": [
      "settings"
    ],
    "capabilities": [
      "settings"
    ]
  },
  {
    "id": "lantern",
    "name": "LANTERN",
    "subtitle": "Carry a little light.",
    "description": "The three lamps as a lamp: colours, brightness and slow scenes, with a night-light that switches itself off.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "INSTRUMENT / LIGHT",
    "glyph": 4,
    "icon": "<path d=\"M19 11q5-8 10 0\"/><path d=\"M17 12h14l4 7v15l-4 6H17l-4-6V19z\"/><path d=\"M13 19h22M13 34h22M15 43h18\"/><circle cx=\"18\" cy=\"27\" r=\"1.6\" fill=\"currentColor\"/><circle cx=\"24\" cy=\"27\" r=\"1.6\" fill=\"currentColor\"/><circle cx=\"30\" cy=\"27\" r=\"1.6\" fill=\"currentColor\"/>",
    "factory": "Lantern",
    "voice": [
      "lamp"
    ],
    "capabilities": [
      "lights",
      "progress"
    ]
  },
  {
    "id": "cadence",
    "name": "CADENCE",
    "subtitle": "Count the beat and the laps.",
    "description": "A metronome with tap tempo, a stopwatch with laps, and work/rest intervals shown on the lamps.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "INSTRUMENT / TEMPO",
    "glyph": 3,
    "factory": "Cadence",
    "voice": [
      "metronome",
      "timer"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "icon": "<path d=\"M16 42h16l5-30H11z\"/><path d=\"M24 36L33 8\"/><circle cx=\"30\" cy=\"19\" r=\"2.5\" fill=\"currentColor\"/><path d=\"M19 42v-5M29 42v-5\"/><path d=\"M40 20q4 4 0 8M43 17q7 7 0 14\"/>"
  },
  {
    "id": "ephemeris",
    "name": "EPHEMERIS",
    "subtitle": "Know where the sky is.",
    "description": "The time, the Moon's phase, sunrise and sunset for your location, and a small orrery. All computed locally.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "INSTRUMENT / SKY",
    "glyph": 0,
    "factory": "Ephemeris",
    "icon": "<path d=\"M4 34h40\"/><path d=\"M12 34a12 12 0 0 1 24 0\"/><path d=\"M24 16v-5M10 22l-3-3M38 22l3-3\"/><path d=\"M38 5a6 6 0 1 0 5 9 5 5 0 0 1-5-9z\"/><circle cx=\"8\" cy=\"42\" r=\"1.5\" fill=\"currentColor\"/><circle cx=\"24\" cy=\"42\" r=\"1.5\" fill=\"currentColor\"/><circle cx=\"40\" cy=\"42\" r=\"1.5\" fill=\"currentColor\"/>",
    "voice": [],
    "capabilities": [
      "progress"
    ]
  },
  {
    "id": "resonance",
    "name": "RESONANCE",
    "subtitle": "See what the room sounds like.",
    "description": "Sound level, spectrum and pitch from the microphone. Nothing is recognised or stored.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "INSTRUMENT / SOUND",
    "glyph": 2,
    "factory": "Resonance",
    "icon": "<rect x=\"5\" y=\"9\" width=\"38\" height=\"30\" rx=\"5\"/><path d=\"M9 24h5l3-9 4 18 4-22 4 20 3-11 2 4h6\"/><path d=\"M9 34h30\" stroke-dasharray=\"1 4\"/><circle cx=\"39\" cy=\"14\" r=\"1.6\" fill=\"currentColor\"/>",
    "voice": [
      "sound"
    ],
    "capabilities": [
      "microphone",
      "lights"
    ]
  },
  {
    "id": "oracle",
    "name": "ORACLE",
    "subtitle": "Ask the dark for a number.",
    "description": "Dice, coins, random picks and yes-or-no answers, rolled across the lamps.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "INSTRUMENT / CHANCE",
    "glyph": 5,
    "factory": "Oracle",
    "icon": "<rect x=\"7\" y=\"7\" width=\"34\" height=\"34\" rx=\"7\"/><circle cx=\"17\" cy=\"17\" r=\"2.4\" fill=\"currentColor\"/><circle cx=\"31\" cy=\"17\" r=\"2.4\" fill=\"currentColor\"/><circle cx=\"24\" cy=\"24\" r=\"2.4\" fill=\"currentColor\"/><circle cx=\"17\" cy=\"31\" r=\"2.4\" fill=\"currentColor\"/><circle cx=\"31\" cy=\"31\" r=\"2.4\" fill=\"currentColor\"/><path d=\"M2 24h2M44 24h2M24 2v2M24 44v2\"/>",
    "voice": [
      "dice"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ]
  },
  {
    "id": "telemetry",
    "name": "TELEMETRY",
    "subtitle": "Listen to the machine itself.",
    "description": "Health of the Pi and the node: temperature, load, memory, storage, link and firmware.",
    "controls": "TAP NEXT · HOLD TO CHOOSE",
    "category": "SYSTEM / HEALTH",
    "glyph": 1,
    "factory": "Telemetry",
    "icon": "<path d=\"M6 38a18 18 0 1 1 36 0\"/><path d=\"M24 38l8-14\"/><path d=\"M10 38h4M34 38h4M24 20v4M12 26l3 2M36 26l-3 2\"/><circle cx=\"24\" cy=\"38\" r=\"2\" fill=\"currentColor\"/><path d=\"M8 44h32\" stroke-dasharray=\"3 3\"/>",
    "voice": [
      "system"
    ],
    "capabilities": [
      "sensor"
    ]
  },
  {
    "id": "crawlspace",
    "name": "CRAWLSPACE",
    "subtitle": "A hammer, a drill, and a deeply unreasonable house.",
    "description": "A turn-based household roguelike through three increasingly strange levels. Tap to move between swing, brace and drill, then hold and release to act; enemies announce their next move and wait for you. Build synergies from useful junk, choose repairs or risky rooms, defeat the house's three bosses, then try a tougher crawl.",
    "controls": "TAP: NEXT CARD · HOLD + RELEASE: DO IT · ENEMIES WAIT",
    "category": "PLAY / ROGUELIKE",
    "glyph": 4,
    "factory": "Crawlspace",
    "voice": [
      "crawl space"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "record": {
      "score": "Score",
      "floor": "Level",
      "pests": "Pests cleared",
      "relics": "Useful finds",
      "heat": "Heat",
      "cleared": "House secured"
    },
    "icon": "<path d=\"M5 20L24 5L43 20M11 18V28H37V18M4 33H44M11 40H16M23 39L27 43M35 39H40\"/><path d=\"M21 28V19H28V28\"/>"
  },
  {
    "id": "supper",
    "name": "SUPPER CLUB",
    "subtitle": "Three pans. One button. A house full of hungry people.",
    "description": "Run a small supper club through four dinner services. Tap to move between pans and hold and release to cook, plate or clean; the kitchen slows while you hold. Combine rice, greens and eggs into ticketed meals. Limited stock, food freshness and three chosen kitchen upgrades make every service a different balancing act.",
    "controls": "TAP: NEXT PAN · HOLD + RELEASE: COOK / PLATE · HOLDING SLOWS TIME",
    "category": "PLAY / STRATEGY",
    "glyph": 4,
    "factory": "Supper",
    "voice": [
      "supper",
      "kitchen"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "record": {
      "score": "Tips",
      "meals": "Meals served",
      "waves": "Services",
      "waste": "Portions wasted",
      "stars": "Stars",
      "won": "Closed happy"
    },
    "icon": "<circle cx=\"22\" cy=\"27\" r=\"13\"/><path d=\"M34 32l10 5M15 19h14M17 10V4M24 10V4M31 11V6\"/>"
  },
  {
    "id": "pocketlinks",
    "name": "POCKET LINKS",
    "subtitle": "Nine small courses. Big little decisions.",
    "description": "Play a full nine-hole round with real bank shots, water, rough, ice and sloping greens. Tap to switch a precise putter for a wall-hopping wedge; hold to freeze the aiming arrow and release to choose power. Plan safe routes or daring shortcuts, with three water mulligans for the round.",
    "controls": "TAP CLUB · HOLD AIM · RELEASE POWER",
    "category": "PLAY / SPORT",
    "glyph": 1,
    "factory": "PocketLinks",
    "voice": [
      "golf",
      "pocket links"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "record": {
      "score": "Score",
      "strokes": "Strokes",
      "par": "Course par",
      "holes": "Holes",
      "birdies": "Birdies or better",
      "aces": "Holes in one",
      "mulligans": "Mulligans used"
    },
    "icon": "<path d=\"M31 36V9l11 5-11 5\"/><ellipse cx=\"30\" cy=\"37\" rx=\"9\" ry=\"3\"/><circle cx=\"12\" cy=\"32\" r=\"4\"/><path d=\"M15 28l8-8\"/>"
  },
  {
    "id": "nightgrid",
    "name": "NIGHT GRID",
    "subtitle": "Keep the neighborhood glowing until dawn.",
    "description": "Restore three neighborhood circuits through ten storm-night shifts. Invest repair kits in feeders, smart meters and cross-ties, then route limited power using visible demand forecasts. Shops earn supplies, stored water cushions outages, and a stable neighborhood builds your score. Nothing happens until you pick: tap to move between cards, hold and release to pick one.",
    "controls": "TAP: NEXT CARD · HOLD + RELEASE: PICK · NO TIME LIMIT",
    "category": "PLAY / STRATEGY",
    "glyph": 4,
    "factory": "NightGrid",
    "voice": [
      "night grid"
    ],
    "capabilities": [
      "button",
      "lights",
      "audio",
      "progress"
    ],
    "record": {
      "score": "Score",
      "service": "Service %",
      "chain": "Stable chain",
      "result": "Dawn report",
      "shifts": "Shifts"
    },
    "icon": "<path d=\"M24 5V15M9 15H39M9 15V25M24 15V25M39 15V25M9 34H39\"/><rect x=\"4\" y=\"25\" width=\"10\" height=\"14\"/><rect x=\"19\" y=\"25\" width=\"10\" height=\"14\"/><rect x=\"34\" y=\"25\" width=\"10\" height=\"14\"/>"
  }
];
export const SECTORS = [{"name": "VOYAGES", "tagline": "Long games to sink an evening into.", "apps": ["perihelion", "outpost", "drift", "ballista", "tideline"]}, {"name": "ARCADE", "tagline": "Quick runs for sharp hands.", "apps": ["orbit", "ricochet", "runner", "reaction", "descent"]}, {"name": "MIND", "tagline": "Memory, reading and pattern.", "apps": ["echo", "glyphs"]}, {"name": "AFTER HOURS", "tagline": "Four slower games for the end of the day.", "apps": ["crawlspace", "supper", "pocketlinks", "nightgrid"]}, {"name": "TOOLS", "tagline": "Useful things for the desk.", "apps": ["lantern", "cadence", "oracle", "morse"]}, {"name": "SENSORS", "tagline": "What the node hears and feels.", "apps": ["environment", "resonance", "transcribe"]}];
export const SYSTEM_APPS = ["settings", "diagnostics", "telemetry"];
export const DEFAULT_SETTINGS = {
  "sound": true,
  "volume": 0.25,
  "crt": true,
  "reducedMotion": false,
  "morseWpm": 10,
  "holdMs": 650,
  "gesturePace": "standard",
  "scanMs": 850,
  "tempUnit": "F",
  "tempOffset": 0,
  "lampLevel": "medium",
  "lampAmbient": true,
  "latencyMs": 0,
  "renderQuality": "auto"
};
