#!/usr/bin/env python3
"""Generate the browser catalog from the authoritative Python package JSON."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from vesper.catalog import load_catalog


def build(check=False):
    data = load_catalog()
    text = '// Generated by scripts/build-catalog.py; edit vesper/catalog.json.\n'
    text += 'export const CARTRIDGES = ' + json.dumps(data['apps'], indent=2, ensure_ascii=False) + ';\n'
    text += 'export const DEFAULT_SETTINGS = ' + json.dumps(data['settings'], indent=2) + ';\n'
    path = ROOT / 'web/apps/catalog.js'
    if check:
        if not path.exists() or path.read_text() != text:
            raise SystemExit('Browser catalog is stale. Run scripts/build-catalog.py.')
    else:
        path.write_text(text)


if __name__ == '__main__':
    build('--check' in sys.argv)
